# Generated by Django 3.1.1 on 2020-09-03 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20200903_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rated',
            field=models.CharField(choices=[('G', 'G'), ('PG', 'PG'), ('PG-13', 'PG-13'), ('R', 'R'), ('NC-17', 'NC-17'), ('Not Rated', 'Not Rated (NR)')], max_length=64),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], max_length=255, null=True),
        ),
    ]
