# Generated by Django 3.1.1 on 2020-09-04 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20200904_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='r_movie',
            new_name='movie',
        ),
    ]
